name: mlops-workflow

on:
    push:
        branches: [develop, main]
        paths:
            - mlops/**
            - .github/workflows/MLOps-CI-Workflow.yml

jobs:
    mlops-matrix-workflow:
        runs-on: ubuntu-latest
        strategy:
            matrix: 
                python-version: [3.11, 3.12]
    
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install Python
              uses: actions/setup-python@v4
              with: 
                python-version: ${{ matrix.python-version }}

            - name: Upgrade Python-pip
              run: |
                python -m pip install --upgrade pip setuptools wheel


            - name: Install Dependecies
              run: |
                python -m pip install -r mlops/mlops-requirements.txt
            
            - name: Train Model
              run: |
                python mlops/train.py
                echo "---- repo root ----"
                ls -la
                echo "---- artifacts ----"
                ls -la artifacts || true
                echo "---- artifacts/mlops ----"
                ls -la artifacts/mlops || true
                echo "---- files found ----"
                find artifacts/mlops -maxdepth 1 -type f ! -name ".gitkeep" -print

            - name: Verify ML artifacts exist
              run: |
                test "$(find artifacts/mlops -maxdepth 1 -type f ! -name '.gitkeep' | wc -l)" -gt 0


            - name: Upload ML Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: mlops-${{ matrix.python-version }}-${{ github.run_id }}
                path: artifacts/mlops/
                retention-days: 30

            
              







