name: mlops-workflow

on:
    push:
        branches: [develop, main]
        paths:
            -  .github/workflows/MLOps-CI-Workflow.yml

jobs:
    mlops-matrix-workflow:
        runs-on: ubuntu-latest
        strategy:
            matrix: 
                python-version: [3.11, 3.12]
    
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Install Python
              uses: actions/setup-python@v4
              with: 
                python-version: ${{ matrix.python-version }}

            - name: Upgrade Python-pip
              run: |
                python -m pip install --upgrade pip setuptools wheel


            - name: Install Dependecies
              run: |
                python -m pip install -r mlops/mlops-requirements.txt
            
            - name: Train Model
              run: | 
                python mlops/train.py
                ls -la artifacts/mlops
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: mlops-${{ matrix.python-version }}-${{ github.run_id }}
                path: artifacts/mlops


            
              







