name: print-name

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/print-name.yml
      
jobs:
  printing:
    runs-on: ubuntu-latest
    steps:
      - name: print-name
        run: echo "Added print-name"
